Repository bmstu-iu9/utp2018-1-chat, pull requests merged in 2018-08, with the labels that each got.

#26 API часть 1
  client/js/chat.js
  client/js/common.js
  client/pages/auth.html
  client/pages/chat_new.html
  server/modules/api/dialog.js
  server/modules/api/index.js
  server/modules/api/user.js
  server/modules/auth/login.js
  server/modules/auth/registration.js
  server/modules/auth/session.js
  server/modules/db/index.js
  server/modules/db/models/dialog.js
  server/modules/db/models/user.js
  server/modules/router/api.js
  server/modules/router/index.js
  server/modules/router/source.js
Labels: feature, ready for review

#28 Документация
  docs/.gitkeep
Labels: ready for review

#33 Небольшие обновления в клиентской и серверной части
  .gitignore
  application/modules/auth/login.js
  application/modules/auth/session.js
  application/modules/db/index.js
  application/modules/utils/converter.js
  application/modules/utils/parser.js
  application/public/fonts/SFUIText-Medium.eot
  application/public/fonts/SFUIText-Medium.ttf
  application/public/fonts/SFUIText-Medium.woff
  application/public/fonts/SFUIText-MediumItalic.eot
  application/public/fonts/SFUIText-MediumItalic.ttf
  application/public/fonts/SFUIText-MediumItalic.woff
  application/public/fonts/SFUIText-Regular.eot
  application/public/fonts/SFUIText-Regular.ttf
  application/public/fonts/SFUIText-Regular.woff
  application/public/fonts/SFUIText-Semibold.eot
  application/public/fonts/SFUIText-Semibold.ttf
  application/public/fonts/SFUIText-Semibold.woff
  application/public/fonts/SFUIText-SemiboldItalic.eot
  application/public/fonts/SFUIText-SemiboldItalic.ttf
  application/public/fonts/SFUIText-SemiboldItalic.woff
Labels: back-end, front-end, ready for review

#34 Обновления по API
  application/modules/api/dialog.js
  application/modules/api/msg.js
  application/modules/api/user.js
  client/css/main.css
  client/img/search3.png
  client/pages/chat_new.html
Labels: back-end, ready for review

#36 Обновлена авторизация
  application/modules/api/dialog.js
  application/modules/api/msg.js
  application/modules/auth/login.js
  application/modules/auth/registration.js
  application/modules/db/index.js
  application/modules/db/models/dialog.js
  application/modules/router/index.js
  client/js/auth.js
  client/js/chat.js
  client/js/common.js
  client/js/crypto.js
  client/js/dialog.js
  client/pages/auth.html
  client/scss/pages/_auth.scss
  client/scss/pages/auth.scss
  lib/gulp/tasks/scripts.js
  lib/gulp/tasks/styles.js
  lib/gulp/tasks/watch.js
Labels: back-end, front-end, ready for review

#38 Исправлена ошибка с созданием папки для БД
  application/data/.gitkeep
Labels: back-end, bug, ready for review
