Repository bmstu-iu9/utp2018-1-chat, pull requests merged in 2018-09, with the labels that each got.

#43 Merge chat-cs & develop
  application/modules/api/dialog.js
  application/modules/api/msg.js
  application/modules/db/index.js
  application/modules/db/models/dialog.js
  client/js/auth.js
  client/js/chat.js
  client/js/dialog.js
  client/js/inputs.js
  client/js/modals.js
  client/pages/chat.html
  client/scss/abstracts/_keyframes.scss
  client/scss/components/_buttons.scss
  client/scss/components/_inputs.scss
  client/scss/components/_modals.scss
  client/scss/layout/_chat.scss
  client/scss/main.scss
  lib/gulp/tasks/scripts.js
Labels: back-end, front-end, ready for review

#45 Базовое взаимодействие клиента с сервером
  application/modules/api/index.js
  application/modules/api/msg.js
  application/modules/api/session.js
  client/js/auth.js
  client/js/chat.js
  client/js/common.js
  client/js/dialog.js
  client/js/modals.js
  client/pages/auth.html
  client/scss/layout/_chat.scss
  lib/gulp/tasks/scripts.js
Labels: back-end, front-end, ready for review

#46 Обновления клиента чата
  client/js/common.js
  client/js/modals.js
  client/pages/chat.html
  client/scss/components/_buttons.scss
  client/scss/components/_modals.scss
  client/scss/layout/_chat.scss
  client/scss/layout/_header.scss
  client/scss/main.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
  client/scss/vendors/_fontawesome.scss
Labels: front-end, ready for review

#51 Прототип поиска
  client/img/button1.png
  client/js/chat.js
  client/pages/chat.html
  client/scss/layout/_chat.scss
Labels: back-end, feature, front-end, ready for review

#50 Прикрепление файла
  client/js/chat.js
  client/pages/chat.html
  client/scss/layout/_chat.scss
  package-lock.json
Labels: feature, front-end, ready for review

#53 Внесение изменений в основную ветку
  application/modules/api/index.js
  application/modules/api/msg.js
  application/modules/api/session.js
  application/modules/db/index.js
  application/modules/log/config.js
  application/modules/log/index.js
  application/modules/router/source.js
  client/img/button1.png
  client/img/logo/logo-full-black-blue.jpg
  client/img/logo/logo-full-blue-white.png
  client/js/auth.js
  client/js/chat.js
  client/js/common.js
  client/js/dialog.js
  client/js/md-parser.js
  client/js/modals.js
  client/pages/auth.html
  client/pages/chat.html
  client/scss/components/_buttons.scss
  client/scss/components/_inputs.scss
  client/scss/components/_modals.scss
  client/scss/layout/_chat.scss
  client/scss/layout/_header.scss
  client/scss/layout/_sidebar.scss
  client/scss/main.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
  client/scss/vendors/_fontawesome.scss
  lib/gulp/tasks/scripts.js
  package-lock.json
Labels: feature, ready for review

#56 Обновление документации
  README.md
  docs/api/README.md
  docs/api/dialog.html
  docs/api/dialog.md
  docs/api/index.html
  docs/api/msg.html
  docs/api/msg.md
  docs/api/session.html
  docs/api/session.md
  docs/api/user.html
  docs/api/user.md
  docs/auth-m.jpg
  docs/chat-m.jpg
  docs/client/README.md
  docs/client/index.html
  docs/developers.html
  docs/gitbook/fonts/fontawesome/FontAwesome.otf
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.eot
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.svg
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.ttf
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.woff
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.woff2
  docs/gitbook/gitbook-plugin-api/api.css
  docs/gitbook/gitbook-plugin-api/api.js
  docs/gitbook/gitbook-plugin-fontsettings/fontsettings.js
  docs/gitbook/gitbook-plugin-fontsettings/website.css
  docs/gitbook/gitbook-plugin-highlight/ebook.css
  docs/gitbook/gitbook-plugin-highlight/website.css
  docs/gitbook/gitbook-plugin-livereload/plugin.js
  docs/gitbook/gitbook-plugin-lunr/lunr.min.js
  docs/gitbook/gitbook-plugin-lunr/search-lunr.js
  docs/gitbook/gitbook-plugin-search/lunr.min.js
  docs/gitbook/gitbook-plugin-search/search-engine.js
  docs/gitbook/gitbook-plugin-search/search.css
  docs/gitbook/gitbook-plugin-search/search.js
  docs/gitbook/gitbook-plugin-sharing/buttons.js
  docs/gitbook/gitbook-plugin-theme-api/theme-api.css
  docs/gitbook/gitbook-plugin-theme-api/theme-api.js
  docs/gitbook/gitbook.js
  docs/gitbook/images/apple-touch-icon-precomposed-152.png
  docs/gitbook/images/favicon.ico
  docs/gitbook/style.css
  docs/gitbook/theme.js
  docs/index.html
  docs/search_index.json
  docs/server/README.md
  docs/server/index.html
  docs/usage.html
Labels: ready for review

#57 Pre-release 0.9.0
  README.md
  docs/api/README.md
  docs/api/dialog.html
  docs/api/dialog.md
  docs/api/index.html
  docs/api/msg.html
  docs/api/msg.md
  docs/api/session.html
  docs/api/session.md
  docs/api/user.html
  docs/api/user.md
  docs/auth-m.jpg
  docs/chat-m.jpg
  docs/client/README.md
  docs/client/index.html
  docs/developers.html
  docs/gitbook/fonts/fontawesome/FontAwesome.otf
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.eot
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.svg
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.ttf
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.woff
  docs/gitbook/fonts/fontawesome/fontawesome-webfont.woff2
  docs/gitbook/gitbook-plugin-api/api.css
  docs/gitbook/gitbook-plugin-api/api.js
  docs/gitbook/gitbook-plugin-fontsettings/fontsettings.js
  docs/gitbook/gitbook-plugin-fontsettings/website.css
  docs/gitbook/gitbook-plugin-highlight/ebook.css
  docs/gitbook/gitbook-plugin-highlight/website.css
  docs/gitbook/gitbook-plugin-livereload/plugin.js
  docs/gitbook/gitbook-plugin-lunr/lunr.min.js
  docs/gitbook/gitbook-plugin-lunr/search-lunr.js
  docs/gitbook/gitbook-plugin-search/lunr.min.js
  docs/gitbook/gitbook-plugin-search/search-engine.js
  docs/gitbook/gitbook-plugin-search/search.css
  docs/gitbook/gitbook-plugin-search/search.js
  docs/gitbook/gitbook-plugin-sharing/buttons.js
  docs/gitbook/gitbook-plugin-theme-api/theme-api.css
  docs/gitbook/gitbook-plugin-theme-api/theme-api.js
  docs/gitbook/gitbook.js
  docs/gitbook/images/apple-touch-icon-precomposed-152.png
  docs/gitbook/images/favicon.ico
  docs/gitbook/style.css
  docs/gitbook/theme.js
  docs/index.html
  docs/search_index.json
  docs/server/README.md
  docs/server/index.html
  docs/usage.html
Labels: ready for review

#58 Добавлена мобильная версия, изменена документация
  README.md
  client/js/common.js
  client/pages/chat.html
  client/scss/layout/_header.scss
  client/scss/layout/_sidebar.scss
  client/scss/main.scss
  client/scss/media/_mobile.scss
  client/scss/media/_tablet.scss
  docs/api/README.md
  docs/api/dialog.md
  docs/api/msg.md
  docs/api/session.md
  docs/api/user.md
  docs/client/README.md
  docs/client/index.html
  docs/server/README.md
  gulpfile.js
  package-lock.json
  package.json
Labels: front-end, ready for review

#59 Pre-release 0.9.1
  README.md
  client/js/common.js
  client/pages/chat.html
  client/scss/layout/_header.scss
  client/scss/layout/_sidebar.scss
  client/scss/main.scss
  client/scss/media/_mobile.scss
  client/scss/media/_tablet.scss
  docs/api/README.md
  docs/api/dialog.md
  docs/api/msg.md
  docs/api/session.md
  docs/api/user.md
  docs/client/README.md
  docs/client/index.html
  docs/server/README.md
  gulpfile.js
  package-lock.json
  package.json
Labels: ready for review

#60 Исправлены ошибки npm
  gulpfile.js
  lib/gulp/tasks/scripts.js
  package-lock.json
  package.json
Labels: bug, ready for review

#62 Минорные обновления
  application/modules/api/dialog.js
  application/modules/api/index.js
  application/modules/api/msg.js
  application/modules/api/session.js
  application/modules/api/user.js
  application/modules/auth/login.js
  application/modules/log/config.js
  application/modules/log/index.js
  application/modules/router/index.js
  application/modules/router/source.js
  application/server.js
  client/js/chat.js
  client/js/dialog.js
  client/pages/chat.html
  client/scss/components/_modals.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
Labels: ready for review

#63 Релиз 1.0.1
  application/modules/api/dialog.js
  application/modules/api/index.js
  application/modules/api/msg.js
  application/modules/api/session.js
  application/modules/api/user.js
  application/modules/auth/login.js
  application/modules/log/config.js
  application/modules/log/index.js
  application/modules/router/index.js
  application/modules/router/source.js
  application/server.js
  client/js/chat.js
  client/js/dialog.js
  client/pages/chat.html
  client/scss/components/_modals.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
Labels: ready for review

#64 Небольшой рефакторинг + исправления в поиске
  application/modules/api/dialog.js
  application/modules/api/user.js
  application/modules/auth/login.js
  application/modules/db/index.js
  client/js/auth.js
  client/js/chat.js
  client/js/css-classes.js
  client/js/dialog.js
  client/js/modals.js
  client/js/notify.js
  client/pages/chat.html
Labels: ready for review

#66 Авторство сообщений и обновление стилей
  client/js/chat.js
  client/scss/layout/_chat.scss
  client/scss/layout/_sidebar.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
Labels: feature, front-end, ready for review

#67 Develop
  client/js/chat.js
  client/scss/layout/_chat.scss
  client/scss/layout/_sidebar.scss
  client/scss/themes/dark-blue.scss
  client/scss/themes/dark.scss
Labels: feature, ready for review
